### ISSUE TITLE
HP Prime port

### ISSUE THREAD

**Issue by boricj** [boricj/epsilon#1]
https://github.com/boricj/epsilon/tree/hp_prime

TODO:
- [x] Make the linker output an ELF file
- [x] Produce something that runs for at least one instruction before crashing inside @Gigi1237's emulator
- [x] Actually initialize the calculator before trying to run epsilon
- [x] Produce a PRIME_OS.ROM file that mere mortals can use
- [ ] Implement HAL inside `ion` for the HP Prime
  - [x] `Ion::Backlight`
  - [ ] `Ion::Battery`
  - [ ] `Ion::Console`
  - [X] `Ion::Display`
  - [x] `Ion::Events`
  - [x] `Ion::Keyboard`
  - [x] `Ion::Led`
  - [ ] `Ion::Power`
  - [ ] `Ion::USB`
- [ ] Fix odd graphical corruptions
- [x] Submit pull request upstream and grab popcorn
- [ ] **World domination**

**Comment by opcod3** [comment]
Very cool project! 

Just be wary me emulator ain't all that reliable. The official firmware does not even run as you probably know. I try to fix stuff as soon as I have time but I haven't been making much progress. If you could contribute a bit too I'd be super grateful and we might actually get a working emulator soon(tm).

**Comment by boricj** [comment]
I'm not worried about the emulator for this project, given how epsilon works there's really not much that can go horribly wrong: inside the main firmware there's no interrupts/syscalls/timers/mass storage/USB/RTC/threads/whatever. If QEMU can handle Rip'Em's `dumbcalc`, a somewhat naive port of epsilon is barely a notch above in difficulty.

I'm thinking about how to proceed with the emulator. Ideally I'd prefer to rebase and clean up both code and history as if we were submitting patches upstream, but we probably want to get enough stuff working to at least run the diagnostics tool first. In the meantime, **if you need me to probe the hardware to figure out something about it, just say the word on Omnimaga and I'll whip out my GDB stub**. I can only probe the hardware with it though, I can't actually debug anything with it.

I'm also thinking about what to do with Rip'Em. Except for me, my disembodied HP Prime and my GDB stub there's pretty much nobody out there who could run this on real hardware. I really need to improve Rip'Em and implement a chainloader that can both boot the official firmware and run a real ELF launcher that can fetch standalone programs inside PRIME_APP.DAT. I may end up switching Rip'Em's HAL with the one from epsilon too.

There's also the issue about bare-metal development on the HP Prime. It's a _royal pain in the a**_ and I'm really not looking forward to it again, so the more I can develop with the emulator the better.

**Comment by opcod3** [comment]
Okay good to know. I was just warning you just in case. I'm not really well versed in the numworks calculator and its firmware. I would've expected it to require more features. But if it requires none of it even better. The more projects for the prime, the more attention to it the better. It would really be nice to get more people/dev's involved. To have a serious rival to the (in my opinion crappy) Ti nspire.

My main worry for the emulation is to have it working in running the official firmware in at least a semi-working state. Well enough as to be able to debug it. My goal for this project, and for the prime, would be to develop something analogous to ndless for the nspire. And to do that I need a way to debug the official firmware without using jtag since I don't own it. Being able to run bare metal code and not have to rely on HP's language is the end goal for me here. So getting patches upstream or whatnot is not really important for me. But if you are interested we'll se what we can do.

Main problem with the emulator right now is the keyboard input. I don't really need anymore GDB dumps but I'm stumped as to why the firmware, or the diag tool are still not acknowledging keypresses. I got interrupts mostly working, timers working, rtc working and still nothing. I'm seriously stumped. I'm not sure if you can provide any assistance. I'd be immensely grateful.

Improving rip’em would be truly a great goal. I’m not sure if it’s feasible but getting to a point where you gdb stub would allow for actual debugging would be absolutely amazing. The thing is though, I’m not really sure what the Prime community would be interested in. A new firmware or modifications to the original? Because right now I think the lack of interest from other developers is really holding back this  amazing calc compared to the competition. Having more people developing would really be of much aid, and having an interesting project is key for attracting attention. And I’m fully on board for whatever project attract developers to this great non-locked platform (compared to TI).

**Comment by debrouxl** [comment]
Unless HP changed something recently wrt. platform lockdown, a Prime sibling to Ndless could be achieved by patching, ahead of time, select areas (to be found by reverse-engineering) of the ELF binary containing the bulk of the OS, and transferring the result to the calculator. No need to look for and exploit vulnerabilities in the OS (which Cyrille de Brébisson, Tim Wessman and colleagues would have to patch quickly, as they publicly stated somewhere on MoHPC years ago).
As long as nobody finds it smart to attack the exam mode either independently from, or on top of, the native code execution framework, HP shouldn't have a reason to lock the platform down.

It would definitely be nice to get more people involved into... well, about anything that raises user and developer interest in low-level stuff on the Prime - but the fact is that has not occurred in the better part of 5 years since the Prime entered the marketplace. That wasn't for a lack of PoCs or research in the first few months of the platform's life, it's just that the platform was, remained and barring a miracle, will remain unpopular.
A working emulator would probably be a significant building block for a community of developers, though.

**Comment by boricj** [comment]
@debrouxl I have my own theories about developers and the HP Prime. The physical calculator itself and the long list of apps/ports of its platform does not appear to be a commercial failure, otherwise HP would've pulled the plug a long time ago. However, that does not necessarily translate, among other things, into native developers.

@Gigi1237 I can think of a couple of reasons why the firmware isn't reacting to keyboard input. I'll look into it.

Also, I'd rather keep this issue on topic, which I intended to use mostly as a TODO list for myself anyways. I suggest having these off-topic discussions at the calculator forums where the calculator communities would see them.

**Comment by boricj** [comment]
So I got far enough that I can trick epsilon inside the simulator into flickering both the update nagging screen and the home screen. Somehow.

Also, I used my GDB stub on my HP Prime to load epsilon. After waiting an eternity and a half of uploading, it behaves exactly the same as the emulator. Somehow.

IT'S ALIVE! IT'S ALIVE!!!

(And I must say, the HP Prime screen is much nicer to the eye)

(Also, gotta stop doing my evil laugh now. I think I'm scaring my roommate at this point)

**Comment by opcod3** [comment]
@boricj Holy crap grat job! This is actually amazing. What's the next step now?

Sorry for spiraling into an ot discussion. I just wanted to warn you against the incompleteness of the emulator and got a bit carried away. I'll stick to the forums from now on.

**Comment by boricj** [comment]
For this port, implementing `Ion::Events`, `Ion::Keyboard` and the sleep functions in order to have a usable calculator. Then fill out the rest of the HAL and generate a PRIME_OS.ROM file as a stopgap until I implement a real ELF launcher.

This will probably end up deprecating Rip'Em as we know it. The HAL is much nicer and the libc and libcxx are far more complete, so maintaining a separate crappy set of libraries is not necessary.

**Comment by boricj** [comment]
I'm having issues with the timers. On the simulator I managed to get things timed right, but the real hardware is way too fast... I'll set timers aside for the moment and work on events, but without a properly working timebase it's not going to be very usable.

**Comment by opcod3** [comment]
Hmmmm, weird. I thought I managed to implement timers properly in the emulator. I'll have to take a look. Probably i set the frequency variable incorrectly.

**Comment by boricj** [comment]
I managed to get the keyboard, events and timers working at last, both on emulator and on hardware. It truly IS alive now...

Quick `mandelbrot(10)` benchmark, to be taken with extreme caution since who knows how the bootloader set up the HP Prime hardware before we get to run:
* NumWorks: 54 s
* HP Prime: 1'07 s

There are some graphical glitches, but it's perfectly usable otherwise. Raw firmware size is currently 932 KiB, very close to the 1 MiB limit we currently have for the mere mortals. I'll try to make a PRIME_OS.ROM tomorrow if I can.

**Comment by boricj** [comment]
I went ahead and submitted the pull request (https://github.com/numworks/epsilon/pull/534). My inner sadist is disappointed by the fact I will not see the NumWorks team's faces (neither HP's too) tomorrow morning when they open it, but at least I've written all the details they need to know inside the comment section.

**Comment by Ecco** [comment]
> My inner sadist is disappointed by the fact I will not see the NumWorks team's faces tomorrow morning when they open it

It's actually not far from "😀"

**Comment by boricj** [comment]
PRIME_OS.ROM fully functional now. I forgot to clear the caches... and turn the backlight on. Silly me >_<

**Comment by boricj** [comment]
Deader than disco.
